<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ServiceHost.Tui</AssemblyName>
    <RootNamespace>ServiceHost.Tui</RootNamespace>
    <Version>15.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceHost.Core\ServiceHost.Core.csproj" />
  </ItemGroup>

</Project>
